// Custom shader file for nova.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

nova/DC0471C8CF18682BB9D298C15954165A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.10156 0.00000
	}

	{
		map textures/nova/railing.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/6B21F7EE52221206E4E03ED58140FDA1
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.68750 0.00000
	}

	{
		map textures/nova/railing.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/DCB5BAAB32EC4EFD8A6D0F64CB56857E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0027.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/pipe_rusty_03.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/B571ED4FB343D86A3388DF508B378DFA
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0026.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/nova/pipe_rusty.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/041CFB9BEEA82A19258BA56F530F6085
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_30.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/94691D130158C588CFFAB6E6B96528C9
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_36.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/AE245715FB80EDAEFFD0A0C4D279997E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_08.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/D1A3C61CE6286725372D6A7713200033
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0021.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_16.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/E538F88438E4E766C6894AC5C6535849
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0020.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}

	{
		map textures/nova/metal_16.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/41464F29890C5F297515507E7B0DF6EC
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_41.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/73C1278C442F9497940B9400A769C4AD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/nova/automat_seite.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/26D84AA55BD1163931524A10F60F087C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/vent_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/F279B0EB195B0F66567C3864BD8B5F55
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/nova/barrel_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/269E1113085737A7E8442E330ABBDC57
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.02344 0.00000
	}

	{
		map textures/nova/barrel_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/1C30B0D4DE0F1A880647203CDE11BAC6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.02344
	}

	{
		map textures/nova/barrel_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/AC996741ABFD339B21BA36102493A76B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.20312 0.07031
	}

	{
		map textures/nova/barrel_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/CFD2BE49F9F6FBD7400223E91E650480
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.01562 0.00000
	}

	{
		map textures/nova/barrel_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/A9DECD338AD433621CA3D804154C7DE7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.81250 0.00781
	}

	{
		map textures/nova/barrel_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/89BAC7FED64E7A03EA44DDEA48759ADC
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.07031 0.00000
	}

	{
		map textures/nova/barrel_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/45597AFD055BFB53AD2C92550E2E9618
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.37500 0.02344
	}

	{
		map textures/nova/barrel_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/BAD6C5F3E30C1603E8D2DBBDCE232BC6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.24219 0.00000
	}

	{
		map textures/nova/barrel_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/42854B3BAA3F017EEB1108B087199A1C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.46094 0.07031
	}

	{
		map textures/nova/barrel_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/119D051C330271B260B0A98B161EED36
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.33594 0.01562
	}

	{
		map textures/nova/barrel_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/F9F65D91718B7731934A7EFF70D0EF1E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.46094 0.02344
	}

	{
		map textures/nova/barrel_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/E9E003D0A21C15297DFE15F41739114D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.01562
	}

	{
		map textures/nova/barrel_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/125B9557AC23039F29AA4554B912D1FA
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.35156 0.00781
	}

	{
		map textures/nova/barrel_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/C2B4BEE0B38F12D923F3A242CC7FD5AF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.46094 0.00781
	}

	{
		map textures/nova/barrel_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/ADA1541B221F3DB5A67CCC8C4192C933
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00781
	}

	{
		map textures/nova/barrel_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/0DCFE4AB44CC70F99EBADA04D4ABA50A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.51562 0.00000
	}

	{
		map textures/nova/barrel_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/C9BBA1AFA4F7E527E800A96F5C9A605A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_28.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/3B584114E9D4349A973082811C94F84D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0024.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_28.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/827891F283F4A99D2F96D684E7AE8AE6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_28.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/655B67AB29786397B9CBCCB9D8CE3EA5
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_29.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/4077C4F0DF13ABED4AEDD19EC05186AB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_31.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/52379FDFF4E4B1322269B87BFEA7DD26
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0019.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_12.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/63AA6EF847CE3B62C89C360243F0D81A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0017.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_12.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/425C90FFD89D871C47DC4993897B5B36
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_12.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/ECBBF0E06E99386D98E1368E9C3262DE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_12.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/A3BB97B422412B81F041444D76529534
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.12500 0.07812
	}

	{
		map textures/nova/metal_23.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/A31B0C0E0ADC71C8207B28F1FCA78DB2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_09.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/7AC73D1A6CEEBCC2C4EFED6A2594DCDB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_09.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/4EB9C2D322DD8603374216EE1EBDDF7D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0013.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_09.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/8CE12D2C95D4C3C39A3E3AA8E0C976D9
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_14.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/BA859594D9E8D773982EB17EA4CA0F35
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/nova/metal_05.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/49BD40C5631CC27CE789A6D04DB6210C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/nova/metal_05.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/13636C2D7BDEC47DA7F2A3ABF8EBAEBF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_05.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/B5A340E9F7720CFDEE914149FFFD3700
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_05.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/DA5F1F28778260B7D2BB50EADF66393B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/6CA6EC130BF920C80C613AD21B1D84DF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0018.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/05A2C65C640BF259137028E82CC8263E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/567C633E620039A3617338E2572F860B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.14062 0.00000
	}

	{
		map textures/nova/metal_24.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/77EB55BEDAA79FC3D8B870A87DF4EF31
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.12500 0.07812
	}

	{
		map textures/nova/metal_20.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/0A356A3BAA4598E8488964579A50973D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_20.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/C276AE4CB639145E571E6917F446113A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_25.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/F2B9EA0EC9E335D0FC8A41AA88B85462
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0023.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_25.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/973EB084BE7E73784135EEBDDF7D4D6F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_25.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/8A3A018943E168820388677C741F35F9
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_25.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/6791A8131FB63A0A402433AA02F57419
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_26.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/7C8465C52FCEF8DBB1A519F7ECA7E35A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_02.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/C2553B8C59295B0B506464BC12F27EC7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0024.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_27.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/5DD581266F3B48D8F63312122211F833
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_19.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/6FB65268C57F79E87B37F6889508D34D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.14062 0.00000
	}

	{
		map textures/nova/metal_18.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/04DF02023D926990FBF1DF6C01F507C5
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/nova/metal_33.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/25A654E620DDA8ECF86C0B18085F56A4
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map textures/nova/metal_33.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/1618684C065EE96496354047A4A18ADF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.14062 0.00000
	}

	{
		map textures/nova/metal_38.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/82E2C048AC1FB64597CCAE8278D1F5F4
{
	qer_editorimage textures/nova/light_02.jpg
	q3map_surfacelight 300
	q3map_lightImage textures/nova/light_01_lightimgage.jpg
	q3map_lightStyle 1
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/nova/light_02.jpg
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/nova/light_02_blend.jpg
		blendfunc GL_ONE GL_ONE
		rgbGen wave sin 0 1 0 0.5
	}
}

nova/6B9FA740AF6B8D1C075A392CEA133022
{
	qer_editorimage textures/nova/light_02.jpg
	q3map_surfacelight 200
	q3map_lightImage textures/nova/light_01_lightimgage.jpg
	q3map_lightStyle 2
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/nova/light_02.jpg
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/nova/light_02_blend.jpg
		blendfunc GL_ONE GL_ONE
		rgbGen wave noise 0.75 0.5 0 20
	}
}

nova/3D87414B389AE755BD31CCDB6C51FBF0
{
	qer_editorimage textures/nova/light_02.jpg
	q3map_surfacelight 200
	q3map_lightImage textures/nova/light_01_lightimgage.jpg
	q3map_lightStyle 2
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.75 0.5 0 20 // style 2
		tcGen lightmap
	}

	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/nova/light_02.jpg
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
	{
		map textures/nova/light_02_blend.jpg
		blendfunc GL_ONE GL_ONE
		rgbGen wave noise 0.75 0.5 0 20
	}
}

nova/4ABA13B42C0DAFD58563762CB850EEAF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/nova/metal_52.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

nova/9749F4E5A854D49B66108B59C97CB1BE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/nova/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/nova/metal_04.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

